# Generated by Django 2.1.5 on 2019-02-09 02:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Endereço de e-mail')),
                ('first_name', models.CharField(max_length=255, verbose_name='Primeiro nome')),
                ('last_name', models.CharField(max_length=255, verbose_name='Sobrenome')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pretensao_salarial', models.FloatField(verbose_name='Pretensão salarial')),
                ('experiencia', models.TextField(max_length=500, verbose_name='Experiência do usuário')),
                ('escolaridade', models.CharField(choices=[('1', 'Sem escolaridade'), ('2', 'Primário'), ('3', 'Ensino Fundamental'), ('4', 'Ensino Médio'), ('5', 'Ensino Superior'), ('6', 'Pos Graduação ou MBA'), ('7', 'Mestrado'), ('8', 'Doutorado'), ('9', 'PHD - Pós Doutorado')], max_length=1, verbose_name='Nível de escolaridade')),
                ('candidato', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.BigIntegerField(verbose_name='CNPJ da empresa')),
                ('atividade', models.CharField(max_length=255, verbose_name='Atividade principal da empresa')),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
